# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopMall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e'),
        ),
    ]
